CREATE TABLE  `ws300` (
    `time` DATETIME NOT NULL ,
    `s0_temp` DECIMAL( 4, 2 ) ,
    `s0_humi` TINYINT UNSIGNED ,
    `s0_status` TINYINT UNSIGNED ,
    `s1_temp` DECIMAL( 4, 2 ) ,
    `s1_humi` TINYINT UNSIGNED ,
    `s1_status` TINYINT UNSIGNED ,
    `s2_temp` DECIMAL( 4, 2 ) ,
    `s2_humi` TINYINT UNSIGNED ,
    `s2_status` TINYINT UNSIGNED ,
    `s3_temp` DECIMAL( 4, 2 ) ,
    `s3_humi` TINYINT UNSIGNED ,
    `s3_status` TINYINT UNSIGNED ,
    `s4_temp` DECIMAL( 4, 2 ) ,
    `s4_humi` TINYINT UNSIGNED ,
    `s4_status` TINYINT UNSIGNED ,
    `s5_temp` DECIMAL( 4, 2 ) ,
    `s5_humi` TINYINT UNSIGNED ,
    `s5_status` TINYINT UNSIGNED ,
    `s6_temp` DECIMAL( 4, 2 ) ,
    `s6_humi` TINYINT UNSIGNED ,
    `s6_status` TINYINT UNSIGNED ,
    `s7_temp` DECIMAL( 4, 2 ) ,
    `s7_humi` TINYINT UNSIGNED ,
    `s7_status` TINYINT UNSIGNED ,
    `s8_temp` DECIMAL( 4, 2 ) ,
    `s8_humi` TINYINT UNSIGNED ,
    `s8_status` TINYINT UNSIGNED ,
    `s9_temp` DECIMAL( 4, 2 ) ,
    `s9_humi` TINYINT UNSIGNED ,
    `s9_status` TINYINT UNSIGNED ,
    `pressure` SMALLINT UNSIGNED ,
    `rain_abs` DECIMAL( 8, 3 ) ,
    `rain_rel` DECIMAL( 8, 3 ) ,
    `wind` DECIMAL( 4, 1 )
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;
